//created on: Nov 18, 2017
package rules

import com.sample.*;
import java.util.*;
import main.java.VitezaDeRotatieActivelor.*;

rule "Viteza de rotatie a activelor in functie de coeficient de rotatie sau de durata unui circuit"

    when
        i: IndicatorFinanciar(conturiCifraDeAfaceri.size()>0, conturiCapitaluriCirculante.size()>0)
    then
        CoeficientDeRotatii c = new CoeficientDeRotatii(i);
        c.setValoareCoeficientDeRotatii();
        insert(c);
        System.out.println("Se poate calcula viteza de rotatie a activelor in functie de cifra de afaceri sau de durata unui circuit ");
        System.out.println("Valoarea Cifra de afaceri : "+calculSumaV(i.getConturiCifraDeAfaceri()));
        System.out.println("Valoarea Capitaluri circulante: "+calculSumaV(i.getConturiCapitaluriCirculante()));
end

rule "Viteza de rotatie a activelor este slaba conform coeficientului de rotatie"
	when
		i: IndicatorFinanciar() and
		c: CoeficientDeRotatii(indicatorFinanciar == i, ValoareCoeficientDeRotatii<1.0)
	then
		c.setTip(TipVitezaDeRotatieActivelor.SLABA);
		System.out.println("Viteza de rotatie a activelor este slaba conform coeficientului de rotatie, valoarea sa fiind "+c.getValoareCoeficientDeRotatii());
end

rule "Viteza de rotatie a activelor este medie conform coeficientului de rotatie"
	when
		i: IndicatorFinanciar() and
		c: CoeficientDeRotatii(indicatorFinanciar == i, ValoareCoeficientDeRotatii==1.0)
	then
		c.setTip(TipVitezaDeRotatieActivelor.MEDIE);
		System.out.println("Viteza de rotatie a activelor este medie conform coeficientului de rotatie, valoarea sa fiind "+c.getValoareCoeficientDeRotatii());
end

rule "Viteza de rotatie a activelor este buna conform coeficientului de rotatie"
	when
		i: IndicatorFinanciar() and
		c: CoeficientDeRotatii(indicatorFinanciar == i, ValoareCoeficientDeRotatii>1.0)
	then
		c.setTip(TipVitezaDeRotatieActivelor.BUNA);
		System.out.println("Viteza de rotatie a activelor este buna conform coeficientului de rotatie, valoarea sa fiind "+c.getValoareCoeficientDeRotatii());
end

/////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Viteza de rotatie a activelor in functie de numarul de rotatie aferent numai stocurilor"

    when
        i: IndicatorFinanciar(conturiCifraDeAfaceri.size()>0, conturiStocGlobalMediu.size()>0)
    then
        NumarulDeRotatiiAferenteStocurilor n = new NumarulDeRotatiiAferenteStocurilor(i);
        n.setValoareNumarulDeRotatiiAferenteStocurilor();
        insert(n);
        System.out.println("Se poate calcula viteza de rotatie a activelor in functie de numarul de rotatii aferente stocurilor ");
        System.out.println("Valoarea Cifra de afaceri : "+calculSumaV(i.getConturiCifraDeAfaceri()));
        System.out.println("Valoarea Stoc global mediu: "+calculSumaV(i.getConturiStocGlobalMediu()));
end

rule "Viteza de rotatie a activelor este slaba conform nr de rotatie aferent numai stocurilor"
	when
		i: IndicatorFinanciar() and
		n: NumarulDeRotatiiAferenteStocurilor(indicatorFinanciar == i, ValoareNumarulDeRotatiiAferenteStocurilor<1.0)
	then
		n.setTip(TipVitezaDeRotatieActivelor.SLABA);
		System.out.println("Viteza de rotatie a activelor este slaba conform nr de rotatie aferent numai stocurilor, valoarea sa fiind "+n.getValoareNumarulDeRotatiiAferenteStocurilor());
end

rule "Viteza de rotatie a activelor este medie conform nr de rotatie aferent numai stocurilor"
	when
		i: IndicatorFinanciar() and
		n: NumarulDeRotatiiAferenteStocurilor(indicatorFinanciar == i, ValoareNumarulDeRotatiiAferenteStocurilor==1.0)
	then
		n.setTip(TipVitezaDeRotatieActivelor.MEDIE);
		System.out.println("Viteza de rotatie a activelor este medie conform nr de rotatie aferent numai stocurilor, valoarea sa fiind "+n.getValoareNumarulDeRotatiiAferenteStocurilor());
end

rule "Viteza de rotatie a activelor este buna conform nr de rotatie aferent numai stocurilor"
	when
		i: IndicatorFinanciar() and
		n: NumarulDeRotatiiAferenteStocurilor(indicatorFinanciar == i, ValoareNumarulDeRotatiiAferenteStocurilor>1.0)
	then
		n.setTip(TipVitezaDeRotatieActivelor.BUNA);
		System.out.println("Viteza de rotatie a activelor este buna conform nr de rotatie aferent numai stocurilor, valoarea sa fiind "+n.getValoareNumarulDeRotatiiAferenteStocurilor());
end

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Viteza de rotatie a activelor in functie de ratele de rotatie folosind viteza de rotatie pe 90 de zile"

    when
        i: IndicatorFinanciar(numarDeRotatii != null)
    then
        RateleDeRotatie r = new RateleDeRotatie(i);
        r.setVitezaInZileFormula90zile1();
        insert(r);
        System.out.println("Se poate calcula viteza de rotatie a activelor in functie de ratele de rotatie folosind viteza de roatie pe 90 de zile ");
end

rule "Viteza de rotatie a activelor este slaba conform ratelor de rotatie folosind viteza de rotatie pe 90 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile<1.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.SLABA);
		System.out.println("Viteza de rotatie a activelor este slaba conform ratei de rotatie folosind viteza de roatie pe 90 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

rule "Viteza de rotatie a activelor este medie conform ratelor de rotatie folosind viteza de rotatie pe 90 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile>1.0 && VitezaInZile<4.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.MEDIE);
		System.out.println("Viteza de rotatie a activelor este medie conform ratei de rotatie folosind viteza de roatie pe 90 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

rule "Viteza de rotatie a activelor este buna conform ratelor de rotatie folosind viteza de rotatie pe 90 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile>4.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.BUNA);
		System.out.println("Viteza de rotatie a activelor este buna conform ratei de rotatie folosind viteza de roatie pe 90 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Viteza de rotatie a activelor in functie de ratele de rotatie folosind viteza de rotatie pe 360 de zile"

    when
        i: IndicatorFinanciar(numarDeRotatii != null)
    then
        RateleDeRotatie r = new RateleDeRotatie(i);
        r.setVitezaInZileFormula360zile1();
        insert(r);
        System.out.println("Se poate calcula viteza de rotatie a activelor in functie de ratele de rotatie folosind viteza de roatie pe 360 de zile ");
end

rule "Viteza de rotatie a activelor este slaba conform ratelor de rotatie folosind viteza de rotatie pe 360 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile<1.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.SLABA);
		System.out.println("Viteza de rotatie a activelor este slaba conform ratei de rotatie folosind viteza de roatie pe 360 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

rule "Viteza de rotatie a activelor este medie conform ratelor de rotatie folosind viteza de rotatie pe 360 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile>1.0 && VitezaInZile<4.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.MEDIE);
		System.out.println("Viteza de rotatie a activelor este medie conform ratei de rotatie folosind viteza de roatie pe 360 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

rule "Viteza de rotatie a activelor este buna conform ratelor de rotatie folosind viteza de rotatie pe 360 de zile"
	when
		i: IndicatorFinanciar() and
		r: RateleDeRotatie(indicatorFinanciar == i, VitezaInZile>4.0)
	then
		r.setTip(TipVitezaDeRotatieActivelor.BUNA);
		System.out.println("Viteza de rotatie a activelor este buna conform ratei de rotatie folosind viteza de roatie pe 360 de zile, valoarea sa fiind "+r.getVitezaInZile());
end

///////////////////////////////////////////////////////////////////////////////////////////////////////////////

function double calculSumaV(List listaConturi){
	double suma=0.0;
    for(Object c:listaConturi){
    	suma+=((ContClient)c).getSuma();
   	}
   	
   	return suma;
}
